name: Flag FBX Files
on:
  pull_request:
    branches:
      - main
    paths:
      - '**.fbx'
permissions:
  pull-requests: write
  contents: write
jobs:
  flag-fbx-files:
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files
        id: fbx_check
        uses: tj-actions/changed-files@v46
        with:
          json: true
          write_output_files: true
          separator: "\n"
          files: '**.fbx'
      - name: Comment on PR if .fbx files found
        if: steps.fbx_check.outputs.any_changed == 'true'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :warning: FBX files detected in this PR. Please ensure that these files are necessary and consider converting them to GLTF format if possible.
            - Changed FBX files: ${{ steps.fbx_check.outputs.all_changed_files }}